# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 1efc26df2ab2b25f05d7b5bfb4badd7a0916bbad10530779e51fdfd1e8bf8f39c4705a959209e03b79a33348acdc594cf9dc6b286a9f179dcc8921b323544f07

test:
  secret_key_base: 8eee74613b2f1d97fcc6ec508bb3a109502ee1912ad94425768a4c477d24fdc6f91ee69941f50e6e18fed891b2bdc83f77ce72b068e3074502221677f2915e5f

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
